# Generated by Django 4.1.1 on 2022-09-16 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='porton')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Porton',
                'verbose_name_plural': 'Portones',
            },
        ),
        migrations.CreateModel(
            name='Remarks_arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Remarks_departures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Departures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('flight_no', models.CharField(max_length=6, unique=True, verbose_name='Numero de vuelo')),
                ('expected_time', models.DateField(null=True, verbose_name='Hora esperada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('gate', models.ManyToManyField(blank=True, related_name='departures_gate', to='arrivals_departures.gate', verbose_name='Porton')),
                ('lugar', models.ManyToManyField(blank=True, related_name='departures', to='arrivals_departures.ciudad', verbose_name='Lugar')),
                ('remarks', models.ManyToManyField(blank=True, related_name='departures_remarks', to='arrivals_departures.remarks_departures', verbose_name='Comentarios')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Llegada',
                'verbose_name_plural': 'Llegadas',
            },
        ),
        migrations.CreateModel(
            name='Arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('flight_no', models.CharField(max_length=6, unique=True, verbose_name='Numero de vuelo')),
                ('expected_time', models.DateField(null=True, verbose_name='Hora esperada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('lugar', models.ManyToManyField(blank=True, related_name='arrivals', to='arrivals_departures.ciudad', verbose_name='Lugar')),
                ('remarks', models.ManyToManyField(blank=True, related_name='arrivals_remark', to='arrivals_departures.remarks_arrivals', verbose_name='Comentarios')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Llegada',
                'verbose_name_plural': 'Llegadas',
            },
        ),
    ]
